/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-red-900/75',
    'bg-red-900',
    'bg-rose-800/75',
    'bg-rose-800',
    'bg-orange-600/75',
    'bg-orange-600',
    'bg-yellow-300/75',
    'bg-yellow-300',
    'bg-zinc-950/75',
    'bg-zinc-950',
    'bg-amber-50/75',
    'bg-amber-50',
    'bg-lime-400/75',
    'bg-lime-400',
    'bg-indigo-500/75',
    'bg-indigo-500',
    'bg-pink-700/75',
    'bg-pink-700',
    'bg-purple-600/75',
    'bg-purple-600',
    'bg-neutral-50/75',
    'bg-neutral-50',
    'bg-emerald-900/75',
    'bg-emerald-900',
    'bg-zinc-900',
    'bg-white',
    'bg-gray-50',
    'bg-zinc-800',
    'bg-zinc-700',
    'bg-black',
    'bg-opacity-80',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-inherit',
    'text-white/90',
    'text-white',
    'text-zinc-900',
    'text-zinc-100',
    'text-zinc-700',
    'text-zinc-300',
    'text-indigo-500',
    'text-indigo-600',
    'text-indigo-400',
    'border-zinc-600',
    'border-indigo-500',
    'hover:bg-zinc-600',
    'disabled:opacity-50',
    'rounded-2xl',
    'shadow-lg',
    'shadow-md',
    'text-4xl',
    'text-5xl',
    'text-lg',
    'font-bold',
    'font-medium',
    'font-normal',
    'leading-normal',
    'leading-tight',
    'font-sans',
    'font-bungee',
    'font-audiowide',
    'font-montserratalts',
    'font-limelight',
    'font-alumnisc',
    'font-headline',
    'h-full',
    'w-full',
    'm-0',
    'p-0',
    'min-w-[320px]',
    'min-h-screen',
    'rounded-lg',
    'border',
    'border-transparent',
    'px-4',
    'py-2',
    'cursor-pointer',
    'transition-colors',
    'no-underline',
    'material-icons',
    'text-base',
    'flex-1'
  ],
  theme: {
    extend: {
      fontFamily: {
        bungee: ['"Bungee Shade"', 'cursive'],
        audiowide: ['"Audiowide"', 'cursive'],
        limelight: ['"Limelight"', 'cursive'],
        montserratalts: ['"Montserrat Alternates"', 'cursive'],
        alumnisc: ['"Alumni Sans SC"', 'cursive'],
        headline: ['"Mozilla Headline"', 'cursive']
      },
    },
  },
  plugins: [],
}