const BLACKLIST_PHRASES = [
  ' w/ A Rarely Seen Short Film',
  'Count Gore presents ',
  ' - Director\'s Cut',
  'DC Moth StorySLAM:',
  'SPX Presents: ',
  'Art House Theater Day: ',
  ' in 35mm',
  '(sensory friendly)',
  '- 40th Anniversary',
  ': 50TH ANNIVERSARY',
  '50th ANNIVERSARY',
  '50th Anniversary',
  '25TH ANNIVERSARY',
  '25th ANNIVERSARY',
  '15th Anniversary Exclusive',
  ' in 70mm',
  'BONUS CONTENT',
  '\\+ BONUS CONTENT',
  'Q&A',
  '\\+ Q&A',
  '(RE-RELEASE)',
  '\\(RE-RELEASE\\)',
  'Mamoru Hosada\'s',
  'Mamoru Hosada’s',
  'A RARELY SEEN SHORT FILM',
  'LOUDER & UNCUT',
  'Panel Discussion',
  '\\+ Panel Discussion',
  'Panel Discussino',
  '\\+ Panel Discussino',
  '(TAMIL)',
  '\\(TAMIL\\)',
  'Early Access',
  'IMAX Presents',
  ': 30th Anniversary',
  // Add any more phrases you want to ignore here
];

export default BLACKLIST_PHRASES;
